// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/payment/presentation/bloc/payment_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/core/services/analytics_service.dart' as _i7;
import 'package:home_service_app/features/payment/domain/entities/payment_result.dart'
    as _i6;
import 'package:home_service_app/features/payment/domain/repositories/payment_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i3.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> processPayment({
    required String? bookingId,
    required int? amount,
    required String? customerName,
    required String? customerPhone,
    required String? customerEmail,
    String? customerAddress,
    String? customerCity,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [], {
              #bookingId: bookingId,
              #amount: amount,
              #customerName: customerName,
              #customerPhone: customerPhone,
              #customerEmail: customerEmail,
              #customerAddress: customerAddress,
              #customerCity: customerCity,
              #description: description,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#processPayment, [], {
                      #bookingId: bookingId,
                      #amount: amount,
                      #customerName: customerName,
                      #customerPhone: customerPhone,
                      #customerEmail: customerEmail,
                      #customerAddress: customerAddress,
                      #customerCity: customerCity,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>> checkPaymentStatus(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkPaymentStatus, [orderId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentStatus>(
                    this,
                    Invocation.method(#checkPaymentStatus, [orderId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> refundPayment({
    required String? paymentId,
    int? amount,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refundPayment, [], {
              #paymentId: paymentId,
              #amount: amount,
              #reason: reason,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#refundPayment, [], {
                      #paymentId: paymentId,
                      #amount: amount,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PaymentResult>>>
  getCustomerPaymentHistory(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPaymentHistory, [customerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PaymentResult>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PaymentResult>>(
                    this,
                    Invocation.method(#getCustomerPaymentHistory, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PaymentResult>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> getPaymentById(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentById, [paymentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#getPaymentById, [paymentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i7.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSignUp({required String? method, String? userType}) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {
              #method: method,
              #userType: userType,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logLogin({required String? method, String? userType}) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {
              #method: method,
              #userType: userType,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logLogout() =>
      (super.noSuchMethod(
            Invocation.method(#logLogout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperties({
    required String? userId,
    String? userType,
    String? zone,
    String? membershipLevel,
    int? totalBookings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperties, [], {
              #userId: userId,
              #userType: userType,
              #zone: zone,
              #membershipLevel: membershipLevel,
              #totalBookings: totalBookings,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBookingCreated({
    required String? bookingId,
    required String? serviceType,
    required double? estimatedPrice,
    String? zone,
    DateTime? scheduledDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBookingCreated, [], {
              #bookingId: bookingId,
              #serviceType: serviceType,
              #estimatedPrice: estimatedPrice,
              #zone: zone,
              #scheduledDate: scheduledDate,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logBookingCancelled({
    required String? bookingId,
    String? reason,
    int? hoursBeforeService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBookingCancelled, [], {
              #bookingId: bookingId,
              #reason: reason,
              #hoursBeforeService: hoursBeforeService,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logJobCompleted({
    required String? jobId,
    required String? workerId,
    required String? serviceType,
    required int? durationMinutes,
    required double? finalPrice,
    double? workerRating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logJobCompleted, [], {
              #jobId: jobId,
              #workerId: workerId,
              #serviceType: serviceType,
              #durationMinutes: durationMinutes,
              #finalPrice: finalPrice,
              #workerRating: workerRating,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPaymentSuccess({
    required String? paymentId,
    required String? bookingId,
    required double? amount,
    required String? method,
    String? couponCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPaymentSuccess, [], {
              #paymentId: paymentId,
              #bookingId: bookingId,
              #amount: amount,
              #method: method,
              #couponCode: couponCode,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPaymentFailed({
    required String? bookingId,
    required double? amount,
    required String? reason,
    String? errorCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPaymentFailed, [], {
              #bookingId: bookingId,
              #amount: amount,
              #reason: reason,
              #errorCode: errorCode,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logWorkerOnline({
    required String? workerId,
    required bool? isOnline,
    String? zone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logWorkerOnline, [], {
              #workerId: workerId,
              #isOnline: isOnline,
              #zone: zone,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logJobOfferReceived({
    required String? workerId,
    required String? jobId,
    required String? serviceType,
    required double? estimatedEarnings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logJobOfferReceived, [], {
              #workerId: workerId,
              #jobId: jobId,
              #serviceType: serviceType,
              #estimatedEarnings: estimatedEarnings,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logJobOfferResponse({
    required String? workerId,
    required String? jobId,
    required bool? accepted,
    int? responseTimeSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logJobOfferResponse, [], {
              #workerId: workerId,
              #jobId: jobId,
              #accepted: accepted,
              #responseTimeSeconds: responseTimeSeconds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logWorkerRegistration({
    required String? workerId,
    required String? nic,
    required List<String>? services,
    int? onboardingTimeMinutes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logWorkerRegistration, [], {
              #workerId: workerId,
              #nic: nic,
              #services: services,
              #onboardingTimeMinutes: onboardingTimeMinutes,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logWorkerVerification({
    required String? workerId,
    required String? status,
    String? rejectionReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logWorkerVerification, [], {
              #workerId: workerId,
              #status: status,
              #rejectionReason: rejectionReason,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logServiceSelected({
    required String? serviceType,
    String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logServiceSelected, [], {
              #serviceType: serviceType,
              #source: source,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSearch({required String? query, int? resultsCount}) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #query: query,
              #resultsCount: resultsCount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logChatMessage({
    required String? chatId,
    required String? senderType,
    required bool? hasAttachment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logChatMessage, [], {
              #chatId: chatId,
              #senderType: senderType,
              #hasAttachment: hasAttachment,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logNotificationReceived({
    required String? type,
    required String? userId,
    bool? opened,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logNotificationReceived, [], {
              #type: type,
              #userId: userId,
              #opened: opened,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logError({
    required String? error,
    String? context,
    String? stackTrace,
    bool? isFatal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logError, [], {
              #error: error,
              #context: context,
              #stackTrace: stackTrace,
              #isFatal: isFatal,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logApiError({
    required String? endpoint,
    required int? statusCode,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logApiError, [], {
              #endpoint: endpoint,
              #statusCode: statusCode,
              #errorMessage: errorMessage,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logAppStartup({
    required int? startupTimeMs,
    bool? fromBackground,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAppStartup, [], {
              #startupTimeMs: startupTimeMs,
              #fromBackground: fromBackground,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenLoadTime({
    required String? screenName,
    required int? loadTimeMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenLoadTime, [], {
              #screenName: screenName,
              #loadTimeMs: loadTimeMs,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logAddToCart({
    required String? serviceType,
    required double? price,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddToCart, [], {
              #serviceType: serviceType,
              #price: price,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPurchase({
    required String? bookingId,
    required double? value,
    required String? serviceType,
    String? coupon,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPurchase, [], {
              #bookingId: bookingId,
              #value: value,
              #serviceType: serviceType,
              #coupon: coupon,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
