// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/booking/presentation/bloc/booking_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/features/booking/domain/entities/booking.dart'
    as _i6;
import 'package:home_service_app/features/booking/domain/repositories/booking_repository.dart'
    as _i3;
import 'package:home_service_app/features/matching/domain/usecases/find_nearest_worker.dart'
    as _i7;
import 'package:home_service_app/features/worker/domain/entities/worker.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingRepository extends _i1.Mock implements _i3.BookingRepository {
  MockBookingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>> createBooking(
    _i6.Booking? booking,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [booking]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>.value(
              _FakeEither_0<_i5.Failure, _i6.Booking>(
                this,
                Invocation.method(#createBooking, [booking]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>> getBooking(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBooking, [bookingId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>.value(
              _FakeEither_0<_i5.Failure, _i6.Booking>(
                this,
                Invocation.method(#getBooking, [bookingId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>> updateBooking(
    String? bookingId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBooking, [bookingId, data]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>.value(
              _FakeEither_0<_i5.Failure, _i6.Booking>(
                this,
                Invocation.method(#updateBooking, [bookingId, data]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelBooking(
    String? bookingId, {
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [bookingId], {#reason: reason}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(
                  #cancelBooking,
                  [bookingId],
                  {#reason: reason},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>> getCustomerBookings(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerBookings, [customerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Booking>>(
                    this,
                    Invocation.method(#getCustomerBookings, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>> getWorkerBookings(
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkerBookings, [workerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Booking>>(
                    this,
                    Invocation.method(#getWorkerBookings, [workerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Booking>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>> getActiveBookingForCustomer(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBookingForCustomer, [customerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Booking?>(
                    this,
                    Invocation.method(#getActiveBookingForCustomer, [
                      customerId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>> getActiveBookingForWorker(
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBookingForWorker, [workerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Booking?>(
                    this,
                    Invocation.method(#getActiveBookingForWorker, [workerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>> assignWorker(
    String? bookingId,
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignWorker, [bookingId, workerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>.value(
              _FakeEither_0<_i5.Failure, _i6.Booking>(
                this,
                Invocation.method(#assignWorker, [bookingId, workerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>> updateBookingStatus(
    String? bookingId,
    _i6.BookingStatus? status, {
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBookingStatus,
              [bookingId, status],
              {#additionalData: additionalData},
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>.value(
              _FakeEither_0<_i5.Failure, _i6.Booking>(
                this,
                Invocation.method(
                  #updateBookingStatus,
                  [bookingId, status],
                  {#additionalData: additionalData},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Booking>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i6.Booking>> watchBooking(
    String? bookingId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchBooking, [bookingId]),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, _i6.Booking>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, _i6.Booking>>);
}

/// A class which mocks [FindNearestWorker].
///
/// See the documentation for Mockito's code generation for more information.
class MockFindNearestWorker extends _i1.Mock implements _i7.FindNearestWorker {
  MockFindNearestWorker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Worker>>> call(
    _i7.FindNearestWorkerParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.Worker>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Worker>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Worker>>>);
}
