// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/payment/payment_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/features/payment/domain/entities/payment_result.dart'
    as _i6;
import 'package:home_service_app/features/payment/domain/repositories/payment_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i3.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> processPayment({
    required String? bookingId,
    required int? amount,
    required String? customerName,
    required String? customerPhone,
    required String? customerEmail,
    String? customerAddress,
    String? customerCity,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [], {
              #bookingId: bookingId,
              #amount: amount,
              #customerName: customerName,
              #customerPhone: customerPhone,
              #customerEmail: customerEmail,
              #customerAddress: customerAddress,
              #customerCity: customerCity,
              #description: description,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#processPayment, [], {
                      #bookingId: bookingId,
                      #amount: amount,
                      #customerName: customerName,
                      #customerPhone: customerPhone,
                      #customerEmail: customerEmail,
                      #customerAddress: customerAddress,
                      #customerCity: customerCity,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>> checkPaymentStatus(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkPaymentStatus, [orderId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentStatus>(
                    this,
                    Invocation.method(#checkPaymentStatus, [orderId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatus>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> refundPayment({
    required String? paymentId,
    int? amount,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refundPayment, [], {
              #paymentId: paymentId,
              #amount: amount,
              #reason: reason,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#refundPayment, [], {
                      #paymentId: paymentId,
                      #amount: amount,
                      #reason: reason,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PaymentResult>>>
  getCustomerPaymentHistory(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerPaymentHistory, [customerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PaymentResult>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PaymentResult>>(
                    this,
                    Invocation.method(#getCustomerPaymentHistory, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PaymentResult>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>> getPaymentById(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentById, [paymentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PaymentResult>(
                    this,
                    Invocation.method(#getPaymentById, [paymentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentResult>>);
}
