// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/chat/presentation/bloc/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/features/chat/domain/repositories/chat_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> createChatRoom({
    required String? bookingId,
    required String? customerId,
    required String? workerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [], {
              #bookingId: bookingId,
              #customerId: customerId,
              #workerId: workerId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#createChatRoom, [], {
                      #bookingId: bookingId,
                      #customerId: customerId,
                      #workerId: workerId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getChatRoom(
    String? chatRoomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatRoom, [chatRoomId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getChatRoom, [chatRoomId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
  getChatRoomByBooking(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatRoomByBooking, [bookingId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, Map<String, dynamic>?>
                >.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
                    this,
                    Invocation.method(#getChatRoomByBooking, [bookingId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> sendMessage({
    required String? chatRoomId,
    required String? senderId,
    required String? message,
    String? messageType,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #senderId: senderId,
              #message: message,
              #messageType: messageType,
              #metadata: metadata,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #chatRoomId: chatRoomId,
                      #senderId: senderId,
                      #message: message,
                      #messageType: messageType,
                      #metadata: metadata,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>> getMessages(
    String? chatRoomId, {
    int? limit = 50,
    String? lastMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [chatRoomId],
              {#limit: limit, #lastMessageId: lastMessageId},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(
                      #getMessages,
                      [chatRoomId],
                      {#limit: limit, #lastMessageId: lastMessageId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>> watchMessages(
    String? chatRoomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessages, [chatRoomId]),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markMessagesAsRead({
    required String? chatRoomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [], {
              #chatRoomId: chatRoomId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#markMessagesAsRead, [], {
                  #chatRoomId: chatRoomId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getUnreadCount({
    required String? chatRoomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [], {
              #chatRoomId: chatRoomId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getUnreadCount, [], {
                  #chatRoomId: chatRoomId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getUserChatRooms(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChatRooms, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getUserChatRooms, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);
}
