// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/worker/presentation/bloc/worker_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:home_service_app/core/errors/failures.dart' as _i6;
import 'package:home_service_app/core/services/location_service.dart' as _i10;
import 'package:home_service_app/features/worker/domain/entities/worker.dart'
    as _i7;
import 'package:home_service_app/features/worker/domain/entities/worker_application.dart'
    as _i9;
import 'package:home_service_app/features/worker/domain/repositories/worker_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkerRepository extends _i1.Mock implements _i4.WorkerRepository {
  MockWorkerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>> createWorker(
    _i7.Worker? worker,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWorker, [worker]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>>.value(
              _FakeEither_0<_i6.Failure, _i7.Worker>(
                this,
                Invocation.method(#createWorker, [worker]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>> getWorker(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorker, [workerId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>>.value(
              _FakeEither_0<_i6.Failure, _i7.Worker>(
                this,
                Invocation.method(#getWorker, [workerId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.Worker>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> uploadNICDocument({
    required String? workerId,
    required _i8.File? file,
    required bool? isFront,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadNICDocument, [], {
              #workerId: workerId,
              #file: file,
              #isFront: isFront,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#uploadNICDocument, [], {
                  #workerId: workerId,
                  #file: file,
                  #isFront: isFront,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> uploadProfilePhoto({
    required String? workerId,
    required _i8.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [], {
              #workerId: workerId,
              #file: file,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#uploadProfilePhoto, [], {
                  #workerId: workerId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateOnlineStatus({
    required String? workerId,
    required bool? isOnline,
    double? lat,
    double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlineStatus, [], {
              #workerId: workerId,
              #isOnline: isOnline,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateOnlineStatus, [], {
                  #workerId: workerId,
                  #isOnline: isOnline,
                  #lat: lat,
                  #lng: lng,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> acceptContract(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptContract, [workerId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#acceptContract, [workerId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> checkNICExists(String? nic) =>
      (super.noSuchMethod(
            Invocation.method(#checkNICExists, [nic]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
              _FakeEither_0<_i6.Failure, bool>(
                this,
                Invocation.method(#checkNICExists, [nic]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.WorkerApplication>> submitApplication(
    _i9.WorkerApplication? application,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitApplication, [application]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i9.WorkerApplication>
                >.value(
                  _FakeEither_0<_i6.Failure, _i9.WorkerApplication>(
                    this,
                    Invocation.method(#submitApplication, [application]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.WorkerApplication>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.WorkerApplication>>
  getApplicationStatus(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationStatus, [workerId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i9.WorkerApplication>
                >.value(
                  _FakeEither_0<_i6.Failure, _i9.WorkerApplication>(
                    this,
                    Invocation.method(#getApplicationStatus, [workerId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.WorkerApplication>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> completeTraining(
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeTraining, [workerId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#completeTraining, [workerId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateLocation({
    required String? workerId,
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [], {
              #workerId: workerId,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateLocation, [], {
                  #workerId: workerId,
                  #lat: lat,
                  #lng: lng,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i10.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTracking =>
      (super.noSuchMethod(Invocation.getter(#isTracking), returnValue: false)
          as bool);

  @override
  _i5.Future<void> startTracking(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#startTracking, [workerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopTracking() =>
      (super.noSuchMethod(
            Invocation.method(#stopTracking, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Position> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i5.Future<_i3.Position>.value(
              _FakePosition_1(this, Invocation.method(#getCurrentPosition, [])),
            ),
          )
          as _i5.Future<_i3.Position>);

  @override
  _i5.Stream<_i3.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i5.Stream<_i3.Position>.empty(),
          )
          as _i5.Stream<_i3.Position>);
}
