// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/customer/presentation/pages/customer_home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/features/customer/domain/repositories/customer_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i3.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getCustomerProfile(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerProfile, [customerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getCustomerProfile, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  createCustomerProfile(String? customerId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomerProfile, [customerId, data]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#createCustomerProfile, [
                      customerId,
                      data,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  updateCustomerProfile(String? customerId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomerProfile, [customerId, data]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#updateCustomerProfile, [
                      customerId,
                      data,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCustomerProfile(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomerProfile, [customerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteCustomerProfile, [customerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getCustomerBookings(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerBookings, [customerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getCustomerBookings, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
  getSavedAddresses(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedAddresses, [customerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<Map<String, dynamic>>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#getSavedAddresses, [customerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> addSavedAddress(
    String? customerId,
    Map<String, dynamic>? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSavedAddress, [customerId, address]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#addSavedAddress, [customerId, address]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> updateSavedAddress(
    String? customerId,
    String? addressId,
    Map<String, dynamic>? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSavedAddress, [
              customerId,
              addressId,
              address,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#updateSavedAddress, [
                      customerId,
                      addressId,
                      address,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSavedAddress(
    String? customerId,
    String? addressId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedAddress, [customerId, addressId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteSavedAddress, [customerId, addressId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
