// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/auth/domain/usecases/sign_in_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:home_service_app/core/errors/failures.dart' as _i6;
import 'package:home_service_app/features/auth/domain/entities/user.dart'
    as _i5;
import 'package:home_service_app/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> verifyPhone({
    required String? phoneNumber,
    required dynamic Function(String)? onCodeSent,
    required dynamic Function(_i7.PhoneAuthCredential)? onVerificationCompleted,
    required dynamic Function(String)? onVerificationFailed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhone, [], {
              #phoneNumber: phoneNumber,
              #onCodeSent: onCodeSent,
              #onVerificationCompleted: onVerificationCompleted,
              #onVerificationFailed: onVerificationFailed,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#verifyPhone, [], {
                  #phoneNumber: phoneNumber,
                  #onCodeSent: onCodeSent,
                  #onVerificationCompleted: onVerificationCompleted,
                  #onVerificationFailed: onVerificationFailed,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> verifyOTP({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
              _FakeEither_0<_i6.Failure, _i5.User>(
                this,
                Invocation.method(#verifyOTP, [], {
                  #verificationId: verificationId,
                  #smsCode: smsCode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> updateUserType(
    String? userId,
    _i5.UserType? userType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserType, [userId, userType]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
              _FakeEither_0<_i6.Failure, _i5.User>(
                this,
                Invocation.method(#updateUserType, [userId, userType]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> markUserOnboarded(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markUserOnboarded, [userId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
              _FakeEither_0<_i6.Failure, _i5.User>(
                this,
                Invocation.method(#markUserOnboarded, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);
}
