import 'package:dartz/dartz.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:home_service_app/core/errors/failures.dart';
import 'package:home_service_app/features/auth/domain/entities/user.dart';
import 'package:home_service_app/features/auth/domain/repositories/auth_repository.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import 'sign_in_test.mocks.dart';

/// Mock classes generated by mockito
@GenerateNiceMocks([MockSpec<AuthRepository>()])

/// Tests for SignIn use case
/// 
/// Phase 4: Testing Infrastructure
void main() {
  late SignIn usecase;
  late MockAuthRepository mockRepository;

  setUp(() {
    mockRepository = MockAuthRepository();
    usecase = SignIn(mockRepository);
  });

  const tPhoneNumber = '+94771234567';
  const tVerificationId = 'test-verification-id';
  
  final tUser = User(
    uid: 'test-uid',
    phoneNumber: tPhoneNumber,
    userType: UserType.customer,
    isOnboarded: true,
  );

  group('execute', () {
    test('should sign in user with valid credentials', () async {
      // Arrange
      when(() => mockRepository.verifyPhone(
            phoneNumber: any(named: 'phoneNumber'),
            onCodeSent: any(named: 'onCodeSent'),
            onVerificationCompleted: any(named: 'onVerificationCompleted'),
            onVerificationFailed: any(named: 'onVerificationFailed'),
          )).thenAnswer((_) async => const Right(null));

      // Act
      final result = await usecase(SignInParams(phoneNumber: tPhoneNumber));

      // Assert
      expect(result, const Right(null));
      verify(() => mockRepository.verifyPhone(
            phoneNumber: tPhoneNumber,
            onCodeSent: any(named: 'onCodeSent'),
            onVerificationCompleted: any(named: 'onVerificationCompleted'),
            onVerificationFailed: any(named: 'onVerificationFailed'),
          )).called(1);
    });

    test('should return failure when repository fails', () async {
      // Arrange
      when(() => mockRepository.verifyPhone(
            phoneNumber: any(named: 'phoneNumber'),
            onCodeSent: any(named: 'onCodeSent'),
            onVerificationCompleted: any(named: 'onVerificationCompleted'),
            onVerificationFailed: any(named: 'onVerificationFailed'),
          )).thenAnswer((_) async => Left(AuthFailure('Invalid phone number')));

      // Act
      final result = await usecase(SignInParams(phoneNumber: tPhoneNumber));

      // Assert
      expect(result, Left(AuthFailure('Invalid phone number')));
    });
  });
}

/// SignIn use case
class SignIn {
  final AuthRepository repository;

  SignIn(this.repository);

  Future<Either<Failure, void>> call(SignInParams params) async {
    return await repository.verifyPhone(
      phoneNumber: params.phoneNumber,
      onCodeSent: (verificationId) {},
      onVerificationCompleted: (credential) {},
      onVerificationFailed: (error) {},
    );
  }
}

/// SignIn use case parameters
class SignInParams {
  final String phoneNumber;

  SignInParams({required this.phoneNumber});
}
