// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/worker/presentation/pages/nic_input_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:home_service_app/core/errors/failures.dart' as _i5;
import 'package:home_service_app/features/worker/domain/entities/worker.dart'
    as _i6;
import 'package:home_service_app/features/worker/domain/entities/worker_application.dart'
    as _i8;
import 'package:home_service_app/features/worker/domain/repositories/worker_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkerRepository extends _i1.Mock implements _i3.WorkerRepository {
  MockWorkerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>> createWorker(
    _i6.Worker? worker,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWorker, [worker]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>>.value(
              _FakeEither_0<_i5.Failure, _i6.Worker>(
                this,
                Invocation.method(#createWorker, [worker]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>> getWorker(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorker, [workerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>>.value(
              _FakeEither_0<_i5.Failure, _i6.Worker>(
                this,
                Invocation.method(#getWorker, [workerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Worker>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> uploadNICDocument({
    required String? workerId,
    required _i7.File? file,
    required bool? isFront,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadNICDocument, [], {
              #workerId: workerId,
              #file: file,
              #isFront: isFront,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#uploadNICDocument, [], {
                  #workerId: workerId,
                  #file: file,
                  #isFront: isFront,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> uploadProfilePhoto({
    required String? workerId,
    required _i7.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [], {
              #workerId: workerId,
              #file: file,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#uploadProfilePhoto, [], {
                  #workerId: workerId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateOnlineStatus({
    required String? workerId,
    required bool? isOnline,
    double? lat,
    double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlineStatus, [], {
              #workerId: workerId,
              #isOnline: isOnline,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateOnlineStatus, [], {
                  #workerId: workerId,
                  #isOnline: isOnline,
                  #lat: lat,
                  #lng: lng,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> acceptContract(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptContract, [workerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#acceptContract, [workerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkNICExists(String? nic) =>
      (super.noSuchMethod(
            Invocation.method(#checkNICExists, [nic]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#checkNICExists, [nic]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.WorkerApplication>> submitApplication(
    _i8.WorkerApplication? application,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitApplication, [application]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.WorkerApplication>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.WorkerApplication>(
                    this,
                    Invocation.method(#submitApplication, [application]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.WorkerApplication>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.WorkerApplication>>
  getApplicationStatus(String? workerId) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationStatus, [workerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.WorkerApplication>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.WorkerApplication>(
                    this,
                    Invocation.method(#getApplicationStatus, [workerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.WorkerApplication>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> completeTraining(
    String? workerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeTraining, [workerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#completeTraining, [workerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateLocation({
    required String? workerId,
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [], {
              #workerId: workerId,
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateLocation, [], {
                  #workerId: workerId,
                  #lat: lat,
                  #lng: lng,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
