// Mocks generated by Mockito 5.4.6 from annotations
// in home_service_app/test/features/worker/presentation/pages/online_toggle_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:geolocator/geolocator.dart' as _i2;
import 'package:home_service_app/core/services/location_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i3.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTracking =>
      (super.noSuchMethod(Invocation.getter(#isTracking), returnValue: false)
          as bool);

  @override
  _i4.Future<void> startTracking(
    String? workerId, {
    Map<String, dynamic>? workerMetadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startTracking,
              [workerId],
              {#workerMetadata: workerMetadata},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopTracking() =>
      (super.noSuchMethod(
            Invocation.method(#stopTracking, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Position> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i4.Future<_i2.Position>.value(
              _FakePosition_0(this, Invocation.method(#getCurrentPosition, [])),
            ),
          )
          as _i4.Future<_i2.Position>);

  @override
  _i4.Stream<_i2.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i4.Stream<_i2.Position>.empty(),
          )
          as _i4.Stream<_i2.Position>);
}
